prefix: "&6&lSpicy&fQoL &8Â» &f"

spawn:
  teleport-sound: true

homes:
  max-homes: 3

tpa:
  timeout-seconds: 60

rtp:
  world: "world"
  radius: 5000
  min-distance-from-0: 200
  attempts: 15
  safe-check: true